# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(949, 876)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(160, 750, 121, 101))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(150, 130, 611, 81))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 630, 121, 101))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 500, 121, 101))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(320, 750, 121, 101))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(320, 500, 121, 101))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(320, 630, 121, 101))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(480, 750, 121, 101))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(480, 500, 121, 101))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(480, 630, 121, 101))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(160, 370, 121, 101))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(480, 370, 121, 101))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(320, 370, 121, 101))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        self.pushButton_13.setGeometry(QtCore.QRect(640, 750, 121, 101))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        self.pushButton_14.setGeometry(QtCore.QRect(640, 500, 121, 101))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(Form)
        self.pushButton_15.setGeometry(QtCore.QRect(640, 370, 121, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_15.setFont(font)  # застосувати шрифт до певного віджета
        self.pushButton_16 = QtWidgets.QPushButton(Form)
        self.pushButton_16.setGeometry(QtCore.QRect(640, 630, 121, 101))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_16.setFont(font)
        self.pushButton_17 = QtWidgets.QPushButton(Form)
        self.pushButton_17.setGeometry(QtCore.QRect(480, 250, 121, 101))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_17.setFont(font)
        self.pushButton_18 = QtWidgets.QPushButton(Form)
        self.pushButton_18.setGeometry(QtCore.QRect(640, 250, 121, 101))
        self.pushButton_18.setMaximumSize(QtCore.QSize(121, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setPointSize(20)
        font.setWeight(75)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_18.setAutoDefault(False)
        self.pushButton_18.setDefault(False)
        self.pushButton_18.setFlat(False)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(Form)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setGeometry(QtCore.QRect(320, 250, 121, 101))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(Form)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setGeometry(QtCore.QRect(160, 250, 121, 101))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(Form)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setGeometry(QtCore.QRect(240, 25, 121, 101))
        self.pushButton_21.setObjectName("pushButton_21")
        self.lineEdit.setFont(font)
        self.pushButton_22 = QtWidgets.QPushButton(Form)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setGeometry(QtCore.QRect(390, 25, 121, 101))
        self.pushButton_22.setObjectName("pushButton_22")
        self.lineEdit.setFont(font)
        self.pushButton_23 = QtWidgets.QPushButton(Form)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setGeometry(QtCore.QRect(540, 25, 121, 101))
        self.pushButton_23.setObjectName("pushButton_23")
        self.lineEdit.setFont(font)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton_2.clicked.connect(self.add_1)
        self.pushButton_6.clicked.connect(self.add_2)

        #Form.setStyleSheet("background-color: grey;")
        # додаємо до віджета стилі за допомогою self.назва віджета.setStyleSheet
        Form.setStyleSheet("""
        QWidget {
            background-color: #10100f;
            font-size: 20px;
            color: black;
        }
        QPushButton {
            border: 5px solid #45a049;
             border-radius: 20px;
            background-color: #42e512;
        }
        QPushButton:hover {
            background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #82cfff, stop:1 #61afef);
        }
        QPushButton:pressed {
            background-color: green;
        }
        
        QLineEdit {
            font-size: 30px;
            color: white;
            border: 10px solid #45a049; 
            border-radius: 20px;
        }
        """)
        #self.pushButton_2.setStyleSheet("background-color: #42e512; color: red; font-size: 30px; border: 2px solid #45a049; border-radius: 20px")


        self.pushButton_9.clicked.connect(self.add_3)
        self.pushButton_16.clicked.connect(self.add_plus)#підключення кнопки 16 для додавання знака +
        self.pushButton_13.clicked.connect(self.do_math)
        self.pushButton_20.clicked.connect(self.do_clear)
        self.pushButton_3.clicked.connect(self.add_4)
        self.pushButton_5.clicked.connect(self.add_5)
        self.pushButton_8.clicked.connect(self.add_6)
        self.pushButton_10.clicked.connect(self.add_7)
        self.pushButton_12.clicked.connect(self.add_8)
        self.pushButton_11.clicked.connect(self.add_9)
        self.pushButton_19.clicked.connect(self.add_d)
        self.pushButton_18.clicked.connect(self.add_dileny)
        self.pushButton_14.clicked.connect(self.add_minus)
        self.pushButton_4.clicked.connect(self.add_0)
        self.pushButton_15.clicked.connect(self.add_mnocheny)
        self.pushButton_7.clicked.connect(self.add_e)
        self.pushButton.clicked.connect(self.add__)
        self.pushButton_17.clicked.connect(self.add_prozent)
        self.pushButton_21.clicked.connect(self.add_stepiny)
        self.pushButton_22.clicked.connect(self.koriny)
        self.pushButton_23.clicked.connect(self.add_speed)

        # підключаємо кнопку для виконання дії


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "+/-"))
        self.pushButton_2.setText(_translate("Form", "1"))
        self.pushButton_3.setText(_translate("Form", "4"))
        self.pushButton_4.setText(_translate("Form", "0"))
        self.pushButton_5.setText(_translate("Form", "5"))
        self.pushButton_6.setText(_translate("Form", "2"))
        self.pushButton_7.setText(_translate("Form", ","))
        self.pushButton_8.setText(_translate("Form", "6"))
        self.pushButton_9.setText(_translate("Form", "3"))
        self.pushButton_10.setText(_translate("Form", "7"))
        self.pushButton_11.setText(_translate("Form", "9"))
        self.pushButton_12.setText(_translate("Form", "8"))
        self.pushButton_13.setText(_translate("Form", "="))
        self.pushButton_14.setText(_translate("Form", "-"))
        self.pushButton_15.setText(_translate("Form", "×"))
        self.pushButton_16.setText(_translate("Form", "+"))
        self.pushButton_17.setText(_translate("Form", "%"))
        self.pushButton_18.setText(_translate("Form", "÷"))
        self.pushButton_19.setText(_translate("Form", "()"))
        self.pushButton_20.setText(_translate("Form", "c"))
        self.pushButton_21.setText(_translate("Form", "^"))
        self.pushButton_22.setText(_translate("Form", "√"))
        self.pushButton_23.setText(_translate("Form", "v"))

    # додаємо нові діїї
    def add_1(self):
        self.lineEdit.setText(self.lineEdit.text() + '1')

    def add_2(self):
        self.lineEdit.setText(self.lineEdit.text() + '2')

    def add_3(self):
        self.lineEdit.setText(self.lineEdit.text() + '3')

    def add_4(self):
        self.lineEdit.setText(self.lineEdit.text() + '4')

    def add_5(self):
        self.lineEdit.setText(self.lineEdit.text() + '5')

    def add_6(self):
        self.lineEdit.setText(self.lineEdit.text() + '6')

    def add_7(self):
        self.lineEdit.setText(self.lineEdit.text() + '7')

    def add_8(self):
        self.lineEdit.setText(self.lineEdit.text() + '8')

    def add_9(self):
        self.lineEdit.setText(self.lineEdit.text() + '9')

    def add_d(self):
        self.lineEdit.setText(self.lineEdit.text() + '( )')

    def add_plus(self):
        self.lineEdit.setText(self.lineEdit.text() + '+')

    def add_dileny(self):
        self.lineEdit.setText(self.lineEdit.text() + ':')

    def add_minus(self):
        self.lineEdit.setText(self.lineEdit.text() + '-')

    def add_0(self):
        self.lineEdit.setText(self.lineEdit.text() + '0')

    def add_mnocheny(self):
        self.lineEdit.setText(self.lineEdit.text() + '*')

    def add_e(self):
        self.lineEdit.setText(self.lineEdit.text() + ',')

    def add__(self):
        self.lineEdit.setText(self.lineEdit.text() + '-')






    def do_math(self):
        try:
            result = self.lineEdit.text().replace(':', '/')
            self.lineEdit.setText(str(eval(result)))
        except Exception as e:
            print(f'Помилка: {e} спитай в гугл, що воно значить')

    def do_clear(self):
        self.lineEdit.setText("")

    def add_prozent(self):
        try:
            expression = self.lineEdit.text()
            if '+' in expression or '-' in expression or '*' in expression or '/' in expression:
                result = eval(expression.replace(':', '/'))
                percent_result = result / 100
                self.lineEdit.setText(str(percent_result))
            else:
                number = float(expression)
                percent_result = number / 100
                self.lineEdit.setText(str(percent_result))
        except Exception as e:
            print(f'Помилка: {e} спитай в гугл, що воно значить')

    def add_stepiny(self):
        self.lineEdit.setText(self.lineEdit.text() + '**')

    def koriny(self):
        try:
            number = float(self.lineEdit.text())
            result = number ** 0.5
            self.lineEdit.setText(str(result))
        except Error:
            self.lineEdit.setText("Помилка")

    def add_speed(self):
        try:

            inputs = self.lineEdit.text().split(",")
            s = float(inputs[0])
            t = float(inputs[1])


            if t == 0:
                self.lineEdit.setText("Помилка: t = 0")
                return


            v = s / t
            self.lineEdit.setText(f"Швидкість: {v:.2f} м/с")
        except Exception as e:
            self.lineEdit.setText("Помилка: некоректні дані")









if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
